[workspace]

members = [
    "a1",
    "a2",
    "a3",
    "a4",
    "a5",
    "a6",
    "a6/a6_benchgen",
    "b1",
    "b2",
    "b3",
    "b4",
    "b5",
    "b6",
    "read_u32",
    "kickstart_macros",
]
