[package]
name = "b1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
read_u32 = { path = "../read_u32" }
kickstart_macros = { path = "../kickstart_macros" }
